# Generated by Django 4.2.8 on 2023-12-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Intituciones',
            },
        ),
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('fechainscripcion', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('', 'SELECCIONA UNA OPCION'), ('reservada', 'RESRVADA'), ('completada', 'COMPLETADA'), ('anulada', 'ANULADA'), ('no asiste', 'NO ASISTE')], max_length=20)),
                ('observacion', models.TextField(blank=True, max_length=150)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calfuan_diego_FINAL_APP.institucion')),
            ],
        ),
    ]
