# Generated by Django 4.2.8 on 2023-12-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calfuan_diego_FINAL_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
